[package]
name = "ggez_inputty"
version = "0.1.0"
authors = ["Ratys <alexander.sepity@gmail.com>"]

[lib]
name = "ggez_inputty"
path = "src/lib.rs"

[features]
default = ["logging"]
logging = ["log"]

[dependencies]
ggez = "0.4"
log = { version = "0.4", optional = true }