[package]
name = "ggez-inputty"
version = "0.1.0"
authors = ["Ratys <alexander.sepity@gmail.com>"]

[features]
default = ["logging"]
logging = ["log"]

[dependencies]
ggez = "0.4"
log = { version = "0.4", optional = true }