[package]
name = "ggez_inputty"
version = "0.1.0"
authors = ["Ratys <alexander.sepity@gmail.com>"]

[lib]
name = "ggez_inputty"
path = "src/lib.rs"

[dependencies]
ggez = "0.4"
log = "0.4"

[dev-dependencies]
chrono = "0.4"
fern = "0.5"